# Generated by Django 3.1 on 2021-12-25 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='categoy_name',
        ),
    ]
